#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSxFgBtRrZRzz4vscZZ7Vpx9wQ2F0eU2p2js"
APP_SECRET: "RZpyXa8otECZdjy5thlJKMcUGJoIQpRp6dR9vXuv25daTbZngJhsR+VQK+5aAwvYXuu2i70/qdR0UhBHmIPBHefpiXh5Olx3RixPczX3M89Tf7qm7Ka2qKNsnF3Za4AAQKD4CTx8Bo+AqekDfc9WIlzLZQ0pMr3W52sZq9tStwZ9+IYXWaY="

#계좌번호 앞 8자리
CANO: "50111066"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: ""